# Generated by Django 2.2.5 on 2019-10-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default='question', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='circle',
            name='posts',
            field=models.ManyToManyField(blank=True, to='app.Post'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='students',
            field=models.ManyToManyField(blank=True, to='app.Student'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='replays',
            field=models.ManyToManyField(blank=True, to='app.Replay'),
        ),
        migrations.AlterField(
            model_name='replay',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='circles',
            field=models.ManyToManyField(blank=True, to='app.Circle'),
        ),
        migrations.AlterField(
            model_name='student',
            name='posts',
            field=models.ManyToManyField(blank=True, to='app.Post'),
        ),
    ]
