# Generated by Django 2.2.5 on 2019-10-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191011_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='circle_posts', to='app.Post'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='circle_students', to='app.Student'),
        ),
        migrations.AlterField(
            model_name='post',
            name='replays',
            field=models.ManyToManyField(blank=True, related_name='post_replays', to='app.Replay'),
        ),
        migrations.AlterField(
            model_name='student',
            name='circles',
            field=models.ManyToManyField(blank=True, related_name='student_circles', to='app.Circle'),
        ),
        migrations.AlterField(
            model_name='student',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='student_posts', to='app.Post'),
        ),
    ]
